/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.LearningPlatfrom.lms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author zeena
 */
public class Forget_pwd extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Forget_pwd.class.getName());
    public static String uname;

    /**
     * Creates new form Forget_password
     */
    public Forget_pwd(String uname) {
        initComponents();
        this.uname=uname;
    }

    /*private Forget_pwd(String uname) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        this.uname=uname;
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fp_panel = new javax.swing.JPanel();
        pwd = new javax.swing.JLabel();
        password_input = new javax.swing.JPasswordField();
        cnfpwd = new javax.swing.JLabel();
        confrim_password = new javax.swing.JPasswordField();
        forgot_password = new javax.swing.JLabel();
        change_pwd_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        fp_panel.setBackground(new java.awt.Color(255, 255, 255));

        pwd.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        pwd.setText("New password:");

        password_input.addActionListener(this::password_inputActionPerformed);

        cnfpwd.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        cnfpwd.setText("Verify password:");

        confrim_password.addActionListener(this::confrim_passwordActionPerformed);

        forgot_password.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        forgot_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgot_password.setText("FORGOT PASSWORD");

        change_pwd_button.setBackground(new java.awt.Color(0, 102, 102));
        change_pwd_button.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        change_pwd_button.setForeground(new java.awt.Color(255, 255, 255));
        change_pwd_button.setText("CHANGE PASSWORD");
        change_pwd_button.addActionListener(this::change_pwd_buttonActionPerformed);

        javax.swing.GroupLayout fp_panelLayout = new javax.swing.GroupLayout(fp_panel);
        fp_panel.setLayout(fp_panelLayout);
        fp_panelLayout.setHorizontalGroup(
            fp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(forgot_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fp_panelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(fp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(change_pwd_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(fp_panelLayout.createSequentialGroup()
                        .addGroup(fp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cnfpwd, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(pwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(fp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(password_input, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(confrim_password))))
                .addGap(30, 30, 30))
        );
        fp_panelLayout.setVerticalGroup(
            fp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fp_panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(forgot_password, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(fp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_input, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(fp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnfpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confrim_password, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(change_pwd_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fp_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fp_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confrim_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confrim_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confrim_passwordActionPerformed

    private void password_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_inputActionPerformed

    private void change_pwd_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_pwd_buttonActionPerformed
        // TODO add your handling code here:
        change_pwd();
    }//GEN-LAST:event_change_pwd_buttonActionPerformed

    String new_pwd,confirm_pwd;
    boolean validation(){
        new_pwd = new String(password_input.getPassword()).trim();
        confirm_pwd = new String(confrim_password.getPassword()).trim();
        String regex = "^(?=(?:.*[A-Za-z]){3,})(?=.*\\d)(?=.*[@$!%*#?&]).+$";
        if(new_pwd.equals("")){
            JOptionPane.showMessageDialog(this, "password can't be empty!");
            return false;
        }
        if(new_pwd.length()<8){
            JOptionPane.showMessageDialog(this, "Password must conatin atleast 8 charactors!");
            return false;
        }
        if(!new_pwd.trim().matches(regex)){
            JOptionPane.showMessageDialog(this, "Password must contain atleast 3 letters, 1 digit and 1 special character!");
            return false;
        }
        if(confirm_pwd.equals("")){
            JOptionPane.showMessageDialog(this, "Confrim password can't be empty!");
            return false;
        }
        if(!confirm_pwd.equals(new_pwd)){
            JOptionPane.showMessageDialog(this, "Confrim password must be equal to password!");
            return false;
        }
        return true;
    }
    void clear_field(){
        confrim_password.setText("");
        password_input.setText("");
    }
    void change_pwd(){
        if(!validation()){
            return;
        }
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/learning","root","");
            String sql = "UPDATE signup set password=? where username=?";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1,new_pwd);
            st.setString(2,uname);
            int r=st.executeUpdate();
            if(r>0){
                JOptionPane.showMessageDialog(this, "Password updated successfully!");
            }
            else{
                JOptionPane.showMessageDialog(this, "Invalid username!");
            }
            con.close();
        } 
        catch (SQLException e) {
            System.getLogger(Forget_pwd.class.getName()).log(System.Logger.Level.ERROR, (String) null, e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Forget_pwd(uname).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton change_pwd_button;
    private javax.swing.JLabel cnfpwd;
    private javax.swing.JPasswordField confrim_password;
    private javax.swing.JLabel forgot_password;
    private javax.swing.JPanel fp_panel;
    private javax.swing.JPasswordField password_input;
    private javax.swing.JLabel pwd;
    // End of variables declaration//GEN-END:variables
}
