/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.LearningPlatfrom.lms;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author zeena
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_panel = new javax.swing.JPanel();
        password_login = new javax.swing.JLabel();
        username_input_login = new javax.swing.JTextField();
        password_input_login = new javax.swing.JPasswordField();
        username_login = new javax.swing.JLabel();
        forget_password = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        login_button = new javax.swing.JButton();
        remember = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        login_panel.setBackground(new java.awt.Color(255, 255, 255));

        password_login.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        password_login.setText("PASSWORD:");

        username_input_login.addActionListener(this::username_input_loginActionPerformed);

        username_login.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        username_login.setText("USERNAME:");

        forget_password.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        forget_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forget_password.setText("FORGOT PASSWORD");
        forget_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forget_passwordMouseClicked(evt);
            }
        });

        login.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("LOGIN");

        login_button.setBackground(new java.awt.Color(0, 102, 102));
        login_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        login_button.setForeground(new java.awt.Color(255, 255, 255));
        login_button.setText("LOGIN");
        login_button.addActionListener(this::login_buttonActionPerformed);

        remember.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        remember.setText("REMEMBER ME");
        remember.addActionListener(this::rememberActionPerformed);

        javax.swing.GroupLayout login_panelLayout = new javax.swing.GroupLayout(login_panel);
        login_panel.setLayout(login_panelLayout);
        login_panelLayout.setHorizontalGroup(
            login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(login_panelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(login_panelLayout.createSequentialGroup()
                                .addComponent(username_login, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(username_input_login, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, login_panelLayout.createSequentialGroup()
                                    .addComponent(password_login, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(password_input_login))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, login_panelLayout.createSequentialGroup()
                                    .addComponent(remember, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(111, 111, 111)
                                    .addComponent(forget_password, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );
        login_panelLayout.setVerticalGroup(
            login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(login)
                .addGap(30, 30, 30)
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_login)
                    .addComponent(username_input_login, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_login)
                    .addComponent(password_input_login, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remember, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forget_password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void username_input_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_input_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_input_loginActionPerformed

    private void rememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rememberActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        // TODO add your handling code here:
        login_check();
        clear_field();
    }//GEN-LAST:event_login_buttonActionPerformed

    private void forget_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forget_passwordMouseClicked
        // TODO add your handling code here:
        String uname=username_input_login.getText();
        if(uname.equals("")){
            JOptionPane.showMessageDialog(this, "Username can't be empty");
            return;
        }
        new Forget_pwd(uname).setVisible(true);
    }//GEN-LAST:event_forget_passwordMouseClicked

    void login_check(){
        if(!validation()){
            return;
        }
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/learning";
            Connection con = DriverManager.getConnection(url,"root","");
            String sql = "SELECT * FROM signup WHERE username=? AND password=?";
            PreparedStatement st = con.prepareStatement(sql);

            st.setString(1, uname);
            st.setString(2, pwd);

            ResultSet rs = st.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "Login Successful");
                // signup_login.logged=true;
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Username or Password");
            }
            con.close();
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    String uname,pwd;
    boolean validation(){
        uname = username_input_login.getText();
        pwd = new String(password_input_login.getPassword());
        if(uname.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Username can't be empty");
            return false;
        }
        if(pwd.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Password can't be empty");
            return false;
        }
        return true;
    }
    void clear_field(){
        username_input_login.setText("");
        password_input_login.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel forget_password;
    private javax.swing.JLabel login;
    private javax.swing.JButton login_button;
    private javax.swing.JPanel login_panel;
    private javax.swing.JPasswordField password_input_login;
    private javax.swing.JLabel password_login;
    private javax.swing.JCheckBox remember;
    private javax.swing.JTextField username_input_login;
    private javax.swing.JLabel username_login;
    // End of variables declaration//GEN-END:variables
}
