/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.LearningPlatfrom.lms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author zeena
 */
public class Register extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        register = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        phone_no = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        course = new javax.swing.JLabel();
        name_input = new javax.swing.JTextField();
        phone_no_input = new javax.swing.JTextField();
        email_input = new javax.swing.JTextField();
        username_input = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        id = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        register.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        register.setText("REGISTER");

        name.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        name.setText("NAME:");

        email.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        email.setText("EMAIL:");

        phone_no.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        phone_no.setText("PHONE NO:");

        username.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        username.setText("USERNAME:");

        course.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        course.setText("COURSE:");

        submit.setBackground(new java.awt.Color(0, 102, 102));
        submit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("SUBMIT");
        submit.addActionListener(this::submitActionPerformed);

        id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1002", "1003", "1004", "1005", "1006", "1007" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(username_input, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(phone_no_input))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(name_input))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(email_input, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 50, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(register)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_no_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        insert_data();
        clear_field();
    }//GEN-LAST:event_submitActionPerformed

    String name_,email_,phone_no_,uname,course_id;
    boolean validation(){
        name_=name_input.getText().trim();
        email_=email_input.getText().trim();
        phone_no_=phone_no_input.getText();
        uname=username_input.getText().trim();
        course_id=id.getSelectedItem().toString();
        String regex="^[A-Za-z0-9._%+-]+@gmail.com";
        System.out.println("Selected Course ID: " + course_id);
        if(name_.equals("")){
            JOptionPane.showMessageDialog(this, "Name can't be empty!");
            return false;
        }
        if(name_.length()<=2){
            JOptionPane.showMessageDialog(this, "Name can't be smaller than 3!");
            return false;
        }
        if(email_.equals("")){
            JOptionPane.showMessageDialog(this, "Email can't be empty!");
            return false;
        }
        if(!email_.matches(regex)){
            JOptionPane.showMessageDialog(this, "Invalid email!");
            return false;
        }
        if(phone_no_.length()!=10||phone_no_.startsWith("0")){
            JOptionPane.showMessageDialog(this, "Invaild Phone number!");
            return false;
        }
        char[] arr=phone_no_.toCharArray();
        for(int i=0;i<10;i++){
            if(!(arr[i]>='0'&&arr[i]<='9')){
                JOptionPane.showMessageDialog(this, "Phone number can conatin only numbers!");
                return false;
            }
        }
        if(uname.equals("")){
            JOptionPane.showMessageDialog(this, "Username can't be empty!");
            return false;
        }
        return true;
    }
    void clear_field(){
        username_input.setText("");
        email_input.setText("");
        name_input.setText("");
        phone_no_input.setText("");
    }
    void insert_data(){
        if(!validation()){
            return;
        }
        Connection con; boolean f1=false,f2=false;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/learning?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
            String sql="insert into enrolled(username, course_id) values(?,?)";
            PreparedStatement st=con.prepareStatement(sql);
            st.setString(1, uname);
            st.setString(2, course_id);
            int rows = st.executeUpdate();
            if(rows > 0) {
                f1 = true;
            }
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Enrolled insert failed: " + ex.getMessage());
        } 
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/learning?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
            String sql = "UPDATE signup SET name=?, email=?, phone_number=? WHERE username=?";
            PreparedStatement st=con.prepareStatement(sql);
            st.setString(1, name_);
            st.setString(2, email_);
            st.setString(3, phone_no_);
            st.setString(4,uname);
            int rows = st.executeUpdate();
            if(rows > 0) {
                f2 = true;
            }
            con.close();;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Signup insert failed: " + ex.getMessage());
        } 
        if(f1==true&&f2==true){
            JOptionPane.showMessageDialog(this, "Data inserted successfully");
        }
        else{
            JOptionPane.showMessageDialog(this, "Data not inserted");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel course;
    private javax.swing.JLabel email;
    private javax.swing.JTextField email_input;
    private javax.swing.JComboBox<String> id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField name_input;
    private javax.swing.JLabel phone_no;
    private javax.swing.JTextField phone_no_input;
    private javax.swing.JLabel register;
    private javax.swing.JButton submit;
    private javax.swing.JLabel username;
    private javax.swing.JTextField username_input;
    // End of variables declaration//GEN-END:variables
}
