/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.LearningPlatfrom.lms;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author zeena
 */
public class Sign_up extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Sign_up.class.getName());

    /**
     * Creates new form Sign_up
     */
    public Sign_up() {
        initComponents();
        setSize(500, 390);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signup_panel = new javax.swing.JPanel();
        cnfpwd = new javax.swing.JLabel();
        signup = new javax.swing.JLabel();
        signup_button = new javax.swing.JButton();
        pwd = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password_input = new javax.swing.JPasswordField();
        username_input = new javax.swing.JTextField();
        confrim_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        signup_panel.setBackground(new java.awt.Color(255, 255, 255));

        cnfpwd.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cnfpwd.setText("CONFRIM PASSWORD:");

        signup.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        signup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signup.setText("SIGN UP");

        signup_button.setBackground(new java.awt.Color(0, 102, 102));
        signup_button.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        signup_button.setForeground(new java.awt.Color(255, 255, 255));
        signup_button.setText("SIGN UP");
        signup_button.addActionListener(this::signup_buttonActionPerformed);

        pwd.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        pwd.setText("PASSWORD:");

        username.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        username.setText("USERNAME:");

        confrim_password.addActionListener(this::confrim_passwordActionPerformed);

        javax.swing.GroupLayout signup_panelLayout = new javax.swing.GroupLayout(signup_panel);
        signup_panel.setLayout(signup_panelLayout);
        signup_panelLayout.setHorizontalGroup(
            signup_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signup_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(signup_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signup_panelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(signup_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(signup_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(signup_panelLayout.createSequentialGroup()
                                .addGroup(signup_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cnfpwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addGroup(signup_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(password_input, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(username_input, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confrim_password, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35))))
        );
        signup_panelLayout.setVerticalGroup(
            signup_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signup_panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(signup)
                .addGap(30, 30, 30)
                .addGroup(signup_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(signup_panelLayout.createSequentialGroup()
                        .addGroup(signup_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username_input, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(cnfpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signup_panelLayout.createSequentialGroup()
                        .addComponent(password_input, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addComponent(confrim_password, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(signup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signup_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signup_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_buttonActionPerformed
        // TODO add your handling code here:
        insert_data();
        clear_field();
    }//GEN-LAST:event_signup_buttonActionPerformed

    private void confrim_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confrim_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confrim_passwordActionPerformed
    String uname,password,c_password;
    void insert_data(){
        if(!validation()){
            return ;
        }
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/learning?zeroDateTimeBehavior=CONVERT_TO_NULL";
            Connection con=DriverManager.getConnection(url, "root", "");
            String sql="insert into signup(username, password) values(?,?)";
            PreparedStatement st=con.prepareStatement(sql);
            st.setString(1,uname);
            st.setString(2, password);
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data inserted successfully");
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println(e.getMessage());
        }
    }
    void clear_field(){
        username_input.setText("");
        password_input.setText("");
        confrim_password.setText("");
    }
    boolean validation(){
        uname=username_input.getText().trim();
        password=new String(password_input.getPassword()).trim();
        c_password=new String(confrim_password.getPassword()).trim();
        String regex = "^(?=(?:.*[A-Za-z]){3,})(?=.*\\d)(?=.*[@$!%*#?&]).+$";
        if(uname.equals("")){
            JOptionPane.showMessageDialog(this, "Username can't be empty!");
            return false;
        }
        if(password.equals("")){
            JOptionPane.showMessageDialog(this, "Password can't be empty!");
            return false;
        }
        if(password.length()<8){
            JOptionPane.showMessageDialog(this, "Password must conatin atleast 8 charactors!");
            return false;
        }
        if(!password.trim().matches(regex)){
            JOptionPane.showMessageDialog(this, "Password must contain atleast 3 letters, 1 digit and 1 special character!");
            return false;
        }
        if(c_password.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Confrim password can't be empty!");
            return false;
        }
        if(!c_password.equals(password)){
            JOptionPane.showMessageDialog(this, "Confrim password must be equal to password!");
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Sign_up().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cnfpwd;
    private javax.swing.JPasswordField confrim_password;
    private javax.swing.JPasswordField password_input;
    private javax.swing.JLabel pwd;
    private javax.swing.JLabel signup;
    private javax.swing.JButton signup_button;
    private javax.swing.JPanel signup_panel;
    private javax.swing.JLabel username;
    private javax.swing.JTextField username_input;
    // End of variables declaration//GEN-END:variables
}
